config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/login'=>'sessions#login'
  post '/sign_in'=>'sessions#sign_in'
  get '/sign_out'=>'sessions#sign_out'
  post '/app/check_update' => 'update_apks#check_update'
  get '/app/latest' => 'update_apks#latest'
  resources :update_apks do
      resources :versions
  end
  resources :versions

end

app/models/update_apk.rb
class UpdateApk < ActiveRecord::Base
    has_many :versions
    DURL = 'http://60.10.135.153:5000/apk/'
    def compare(uuid,version)
        result = {}
        vs = self.class.find_by_uuid(uuid)
        if vs.nil?
            result[:errorInfo] = "找不到这个AppKey。"
            result[:errorCode] = -1 
            return result
        end
        vs = vs.versions
        if vs.size == 0
            result[:errorInfo] = "未找到任何版本。"
            result[:errorCode] = -1
            return result
        end
        ft = ["0.0.0",nil,'不强制更新']
        vs.each do |l|
            if diff(l.version,ft[0]) == 1
                ft[0] = l.version
                ft[1] = l.filename
                ft[2] = l.state if l.state == '强制更新'
            end
        end
        case diff(ft[0],version)
        when -1
            result[:errorInfo] = '用户版本高于数据库版本.'
            result[:errorCode] = -1
        when 0
            result[:errorInfo] = '用户版本是最新版本.'
            result[:errorCode] = 1000
            result[:isUpdate] = 'no'
        when 1
            result[:errorInfo] = '用户版本不是最新版本'
            result[:errorCode] = 1000
            ft[2] == '强制更新' ? result[:isUpdate] = 'must' : result[:isUpdate] = 'yes'
        end
        result[:downloadUrl] = DURL+ft[1]
        result
    end

    #获取最新版本app，异常返回真财网
    def latest(uuid)
        begin
            filename = DURL+self.class.find_by_uuid(uuid).versions.order(updated_at: :desc).first.filename
        rescue
            filename = 'http://www.zc12369.com'
        end
    end

    private
    def diff(v1,v2)
        v1 = v1.split('.')
        v2 = v2.split('.')
        (0..2).each do |n|
            v = (v1[n] <=> v2[n])
            return v if v == 1
            return v if v == -1 
        end
        return 0
    end
end

app/controllers/update_apks_controller.rb
class UpdateApksController < SessionsController
    before_action :is_login, except: :latest
    before_action :set_update_apk, only: [:show, :edit, :update, :destroy]
    protect_from_forgery except: :check_update
    # GET /update_apks
    # GET /update_apks.json
    def index
        puts session[:user_id]
        @update_apks = UpdateApk.all
    end

    # GET /update_apks/1
    # GET /update_apks/1.json
    def show
    end

    # GET /update_apks/new
    def new
        @update_apk = UpdateApk.new(uuid:UUIDTools::UUID.timestamp_create.to_s)
    end

    # GET /update_apks/1/edit
    def edit
    end

    #比较版本
    def check_update
        respond_to do |format|
            format.json{render json: UpdateApk.new.compare(params[:appKey],params[:version]) }
        end
    end

    # POST /update_apks
    # POST /update_apks.json
    def create
        @update_apk = UpdateApk.new(update_apk_params)
        # @update_apk.uuid = UUIDTools::UUID.timestamp_create.to_s
        respond_to do |format|
            if @update_apk.save
                format.html { redirect_to @update_apk, notice: 'Update apk was successfully created.' }
                format.json { render :show, status: :created, location: @update_apk }
            else
                format.html { render :new }
                format.json { render json: @update_apk.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /update_apks/1
    # PATCH/PUT /update_apks/1.json
    def update
        respond_to do |format|
            if @update_apk.update(update_apk_params)
                format.html { redirect_to @update_apk, notice: 'Update apk was successfully updated.' }
                format.json { render :show, status: :ok, location: @update_apk }
            else
                format.html { render :edit }
                format.json { render json: @update_apk.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /update_apks/1
    # DELETE /update_apks/1.json
    def destroy
        @update_apk.destroy
        respond_to do |format|
            format.html { redirect_to update_apks_url, notice: 'Update apk was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def latest
        if !params[:appKey]
            render :file=>'/public/404.html',:status=>404
        else
            redirect_to UpdateApk.new.latest(params[:appKey])
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_update_apk
        @update_apk = UpdateApk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_apk_params
        params.require(:update_apk).permit(:name,:uuid)
    end
end

app/helpers/update_apks_helper.rb
module UpdateApksHelper
end

app/views/update_apks/edit.html.erb
<h1>Editing update_apk</h1>

<%= form_for(@update_apk) do |f| %>
    <% if @update_apk.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@update_apk.errors.count, "error") %> prohibited this update_apk from being saved:</h2>

            <ul>
                <% @update_apk.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :App名称 %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :AppKey %><br>
        <%= f.object.uuid %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Show', @update_apk %> |
<%= link_to 'Back', update_apks_path %>

app/views/update_apks/index.html.erb
<h1>Listing update_apks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>AppKey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @update_apks.each do |update_apk| %>
      <tr>
        <td><%= update_apk.name %></td>
        <td><%= update_apk.uuid %></td>
        <td><%= link_to 'Show', update_apk %></td>
        <td><%= link_to 'Edit', edit_update_apk_path(update_apk) %></td>
        <td><%= link_to 'Destroy', update_apk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Show Version', update_apk_versions_path(update_apk) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Update apk', new_update_apk_path %>

app/views/update_apks/new.html.erb
<h1>New update_apk</h1>

<%= form_for(@update_apk) do |f| %>
    <% if @update_apk.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@update_apk.errors.count, "error") %> prohibited this update_apk from being saved:</h2>

            <ul>
                <% @update_apk.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :App名称 %><br>
        <%= f.text_field :name ,size:'50px' %>
    </div>
    <div class="field">
        <%= f.label :AppKey %><br>
        <%= f.text_field :uuid,readonly:'readonly',size:'50px' %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', update_apks_path %>

app/views/update_apks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @update_apk.name %>
</p>

<p>
  <strong>AppKey:</strong>
  <%= @update_apk.uuid %>
</p>

<%= link_to 'Edit', edit_update_apk_path(@update_apk) %> |
<%= link_to 'Back', update_apks_path %>