config/routes.rb
Rails.application.routes.draw do
  resources :users
  get '/login'=>'sessions#login'
  post '/sign_in'=>'sessions#sign_in'
  get '/sign_out'=>'sessions#sign_out'
  post '/app/check_update' => 'update_apks#check_update'
  get '/app/latest' => 'update_apks#latest'
  resources :update_apks do
      resources :versions
  end
  resources :versions

end

app/models/version.rb
class Version < ActiveRecord::Base
    belongs_to :update_apk
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
    before_action :set_version, only: [:show, :edit, :update, :destroy]
    before_action :set_update_apk,only:[:index,:new,:edit,:create,:update,:destroy]
    before_action :save_file,only:[:create,:update]

    # GET /versions
    # GET /versions.json
    def index
        @versions = @update_apk.versions
    end

    # GET /versions/1
    # GET /versions/1.json
    def show
    end

    # GET /versions/new
    def new
        @version = Version.new(update_apk_id:params['update_apk_id'])
    end

    # GET /versions/1/edit
    def edit
    end

    # POST /versions
    # POST /versions.json
    def create
        @version = Version.new(version_params)
        @version.filename = params['version']['file'].original_filename
        @version.update_apk_id = version_params['update_apk_id'].to_i
        respond_to do |format|
            if @version.save
                format.html { redirect_to @version, notice: 'Version was successfully created.' }
                format.json { render :show, status: :created, location: @version }
            else
                format.html { render :new }
                format.json { render json: @version.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /versions/1
    # PATCH/PUT /versions/1.json
    def update
        @version.filename = version_params.original_filename
        respond_to do |format|
            if @version.update(version_params)
                format.html { redirect_to @version, notice: 'Version was successfully updated.' }
                format.json { render :show, status: :ok, location: @version }
            else
                format.html { render :edit }
                format.json { render json: @version.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /versions/1
    # DELETE /versions/1.json
    def destroy
        @version.destroy
        respond_to do |format|
            format.html { redirect_to update_apk_versions_path(@update_apk), notice: 'Version was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
        @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
        params.require(:version).permit(:update_apk_id,:state,:version)
    end

    def set_update_apk
        if params['update_apk_id']
            @update_apk = UpdateApk.find(params['update_apk_id'])
        end
    end
    def save_file
        if Rails.env == 'development'
            file = '/Users/baoxi/Workspace/temp/'+params['version']['file'].original_filename
        elsif Rails.env == 'production'
            file = '/vagrant/static/apk/'+params['version']['file'].original_filename
        end
        if File.exist?(file)
            File.delete(file)
        end
        File.open(file,'wb') do |f|
            f.write(params['version']['file'].read)
        end
    end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<%= form_for(@version) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :update_apk_id, value:@update_apk.id %>
  <div class="field">
    <%= f.label :版本 %><br>
    <%= f.text_field :version,onkeypress:"return (/[/\d/./].test(String.fromCharCode(event.keyCode)))",onkeyup:"inputWarning(this)",style:"ime-mode:Disabled"%>
    <label id='inputWarning'></label>
  </div>
  <div class="field">
    <%= f.label :更新设置 %><br>
    <%= f.select(:state,options_for_select([['不强制更新','不强制更新'],['强制更新','强制更新']],'不强制更新')) %>
  </div>
  <div class="field">
    <%= f.label :选择文件 %><br>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
    function inputWarning(ob){
        if(!ob.value.match(/^\d+.\d+.\d+$/)){
            $("#inputWarning").html("请注意格式:1.2.34");
            $('.actions>input').attr('disabled','disabled');
        }else{
            $("#inputWarning").html("");
            $('.actions>input').removeAttr('disabled');
        }
    }
</script>

app/views/versions/edit.html.erb
<h1>Editing version</h1>
<h2><%= @update_apk.name %></h2>
<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', update_apk_versions_path(@update_apk) %>

app/views/versions/index.html.erb
<h1>Listing versions</h1>
<h2><%= @update_apk.name %></h2>
<table>
  <thead>
    <tr>
      <th>版本</th>
      <th>更新设置</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.version %></td>
        <td><%= version.state %></td>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_update_apk_version_path(@update_apk,version) %></td>
        <td><%= link_to 'Destroy', update_apk_version_path(@update_apk,version), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建', new_update_apk_version_path(@update_apk) %>
<%= link_to 'Back', update_apks_path %>

app/views/versions/new.html.erb
<h1>New version</h1>
<h2><%= @update_apk.name %></h2>
<%= render 'form' %>

<%= link_to 'Back', update_apk_versions_path(@update_apk) %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @version.update_apk.name %></h2>
<p>
  <strong>版本:</strong>
  <%= @version.version %>
  <strong>更新设置:</strong>
  <%= @version.state %>
</p>

<%# <%= link_to 'Edit', edit_update_apk_version_path(@version) %1> | %>
<%= link_to 'Edit', edit_update_apk_version_path(@version.update_apk,@version) %> |
<%= link_to 'Back', update_apk_versions_path(@version.update_apk,@version) %>